---

- name: deploy_rar
  shell: >
    {{ asadminPath }}/asadmin --host localhost --port {{ port }} --user {{ user }}
    --passwordfile {{ pwdFilePath }}/{{ appname }}/{{ pwdFileName }} deploy
    --type rar --name {{ rarName }} {{ rarLocation }}

- name: create_resource_adapter
  shell: >
    {{ asadminPath }}/asadmin --host localhost --port {{ port }} --user {{ user }}
    --passwordfile {{ pwdFilePath }}/{{ appname }}/{{ pwdFileName }} create-resource-adapter-config
    --property ServerUrl={{ activeMQUrl }}:UserName={{ activeMQUser }}:Password={{ activeMQPassword }} {{ rarName }}

- name: create_connection_pool
  shell: >
    {{ asadminPath }}/asadmin --host localhost --port {{ port }} --user {{ user }}
     --passwordfile {{ pwdFilePath }}/{{ appname }}/{{ pwdFileName }} create-connector-connection-pool
     --raname {{ rarName }} --connectiondefinition javax.jms.ConnectionFactory --ping true --isconnectvalidatereq true {{ poolName }}

- name: create_connection_factory
  shell: >
    {{ asadminPath }}/asadmin --host localhost --port {{ port }} --user {{ user }}
    --passwordfile {{ pwdFilePath }}/{{ appname }}/{{ pwdFileName }} create-connector-resource
    --poolname {{ poolName }} {{ factoryName }}

- name: create_login_queue
  shell: >
    {{ asadminPath }}/asadmin --host localhost --port {{ port }} --user {{ user }}
    --passwordfile {{ pwdFilePath }}/{{ appname }}/{{ pwdFileName }} create-admin-object
    --raname {{ rarName }} --restype javax.jms.Queue --property PhysicalName={{ loginQueueName }} jms/{{ loginQueueName }}

- name: create_startup_queue
  shell: >
    {{ asadminPath }}/asadmin --host localhost --port {{ port }} --user {{ user }}
    --passwordfile {{ pwdFilePath }}/{{ appname }}/{{ pwdFileName }} create-admin-object
    --raname {{ rarName }} --restype javax.jms.Queue --property PhysicalName={{ applicationQueueName }} jms/{{ applicationQueueName }}

- name: create_bot_queue
  shell: >
    {{ asadminPath }}/asadmin --host localhost --port {{ port }} --user {{ user }}
    --passwordfile {{ pwdFilePath }}/{{ appname }}/{{ pwdFileName }} create-admin-object
    --raname {{ rarName }} --restype javax.jms.Queue --property PhysicalName={{ botQueueName }} jms/{{ botQueueName }}
