---
- hosts: all
  tasks:
    - name: including vars
      include_vars: vars.yml

    - name: checking java installed or not
      include_role:
        name: prerequisite_check
        tasks_from: check_java.yml

    - name: installing java
      include_role:
        name: prerequisite_check
        tasks_from: install_java.yml
      when:
        - java_check is skipped
        - proceed_installation

    - name: checking payara installed or not
      include_role:
        name: prerequisite_check
        tasks_from: check_payara.yml
      when: proceed_installation

    - name: Installing payara
      include_role:
        name: prerequisite_check
        tasks_from: install_payara.yml
      when:
        - proceed_installation
        - payara_status is skipped
        - proceed_install_payara
      ignore_errors: true

    - name: block for domain check
      block:
        - name: check if domain already present
          stat:
            path: /payara/ESOA/payara-domains/
          register: domain_present
        - name: domain already present
          fail:
            msg: domain is already present
          when: domain_present.stat.exists
        - name: calling role to create domain
          include_role:
            name: create_payara_domain
          when: proceed_install_payara
      when: proceed_installation
