---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: execute command
      shell: xmllint --xpath '//config[@name="server-config"]/network-config/network-listeners/network-listener[@name="admin-listener"]/@port' /payara/ESOA/payara-domains/ansible_test302/config/domain.xml | sed -e 's/^[^"]*"//' -e 's/"$//'
      register: result
      become: true

    - name: debug result
      debug:
        msg: "{{ result }}"
