---
# tasks file for roles/update_existing_domain

- name: update existing domain
  shell: >
    {{ asadminPath }}/asadmin --host localhost --port {{ port }} --user {{ user }}
    --passwordfile {{ pwdFilePath }}/{{ appname }}/{{ pwdFileName }} create-admin-object
    --raname {{ rarName }} --restype {{ class_type[type] }} --property PhysicalName={{ resourcename }} jms/{{ resourcename }}

