---

- name: create directory
  file:
    path: "{{ payaraPath }}"
    state: directory

- name: Extract payara zip file
  unarchive:
    src: "{{ softwarePath }}/Admin/payara-4.1.2.181.zip"
    dest: "{{ payaraPath }}"
  become: true

- name: change permission for payara directory
  become: true
  file:
    name: "{{ payaraPath }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: true

- name: change permission for asadmin
  become: true
  file:
    name: "{{ payaraPath }}/payara-4.1.2.181/glassfish/bin/asadmin"
    mode: '0744'
    owner: root
    group: root

- name: adding as java in asenv.conf
  become: true
  lineinfile:
    path: '/payara/payara/payara-4.1.2.181/glassfish/config/asenv.conf'
    line: 'AS_JAVA="/payara/java/jdk1.8.0_275"'
